admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }


admin_security:
    path : /users
    defaults:
      _controller: AdminBundle:Security:index


admin_marques:
   path : /marques
   defaults: 
     _controller : AdminBundle:Marque:index

admin_marques_add:
    path: /marques/ajout
    defaults:
     _controller: AdminBundle:Marque:add   

admin_marques_edit:
    path: /marques/edit/{id}
    defaults:
      _controller: AdminBundle:Marque:edit
    requirements:
      id: \d+

admin_marques_delete:
    path: /marques/delete/{id}
    defaults:
      _controller: AdminBundle:Marque:delete
    requirements:
      id: \d+

